---
- name: Main playbook to install required tools
  hosts: localhost
  gather_facts: false
  vars:
    packages:
      - curl
      - cmake
      - redis
      - unzip
      - tar
      - git
      - zsh
      - tmux
      - stow
      - screen
      - rsync
      - fd-find
      - ripgrep

  tasks:
    - name: Install required packages
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes

- import_playbook: zsh_setup.yml
- import_playbook: neovim.yml
- import_playbook: tmux.yml
#- import_playbook: docker.yml
- import_playbook: ruby.yml
- import_playbook: python.yml
# - import_playbook: nodejs.yml
- import_playbook: golang.yml
- import_playbook: rustlang.yml
- import_playbook: lazygit.yml
- import_playbook: git_setup.yml
