---
- name: Install Base Packages
  hosts: localhost
  gather_facts: false
  vars:
    packages:
      - curl
      - cmake
      - redis
      - unzip
      - tar
      - git
      - zsh
      - tmux
      - stow
      - screen
      - rsync
      - fd-find
      - ripgrep

  tasks:
    - name: Install required packages
      become: true
      apt:
        name: "{{ packages }}"
        state: present
        update_cache: yes
