---
- name: Configure TMUX enviroment
  hosts: localhost
  become: yes
  vars:
    user_home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    dotfiles_directory: "{{ lookup('env', 'HOME') }}/.dotfiles"
    packages:
      - tmux
      - stow
      - tmuxinator
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ packages }}"
        state: present
    - name: Clone tpm
      git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: ~/.tmux/plugins/tpm
    - name: Stow dotfiles
      shell: stow -t ~ tmux
      args:
        chdir: "{{ dotfiles_directory }}"

    - name: Change ownership of .config and .dotfiles
      file:
        path: "{{ item }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes
      with_items:
        - "{{ user_home }}/.config"
        - "{{ user_home }}/.dotfiles"
