---
- name: Configure Zsh environment
  hosts: localhost
  become: yes
  become_method: sudo
  vars:
    packages:
      - curl
      - zsh
      - git
      - stow
    user_home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    current_shell: "{{ lookup('env', 'SHELL') }}"
    dotfile_repo: "https://github.com/aenrione/dotFiles"
  tasks:
    - name: Ensure required packages are installed
      package:
        name: "{{ packages }}"
        state: present

    - name: Change default shell to Zsh
      user:
        name: "{{ user }}"
        shell: /usr/bin/zsh
      when: current_shell != '/usr/bin/zsh'

    - name: Clone zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "{{ user_home }}/.zsh/zsh-autosuggestions"
      become: no

    - name: Remove existing zsh configuration files
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ user_home }}/.zshrc"
        - "{{ user_home }}/.config/shell"
      become: no

    - name: Clone dotfiles repository
      git:
        repo: "{{dotfile_repo}}"
        dest: "{{ user_home }}/.dotfiles"
        force: yes
      become: no

    - name: Apply dotfiles using Stow
      command: stow -t "{{ user_home }}" zsh
      args:
        chdir: "{{ user_home }}/.dotfiles"
      become: no

    - name: Change ownership of .config and .dotfiles
      file:
        path: "{{ item }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        recurse: yes
      with_items:
        - "{{ user_home }}/.config"
        - "{{ user_home }}/.dotfiles"
