---
- name: Configure Zsh environment
  hosts: localhost
  become: yes
  become_method: sudo
  vars:
    packages:
      - curl
      - zsh
      - git
      - stow
    user_home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    current_shell: "{{ lookup('env', 'SHELL') }}"
  tasks:
    - name: CHSH ZSH
      shell: chsh -s /usr/bin/zsh {{ user }}
      when: current_shell != '/usr/bin/zsh'

    - name: Clone zsh-nvm plugin
      git:
        repo: https://github.com/lukechilds/zsh-nvm.git
        dest: "{{ user_home }}/.zsh-nvm"
      become: no

    - name: Clone zsh-autosuggestions
      git:
        repo: https://github.com/zsh-users/zsh-autosuggestions.git
        dest: "{{ user_home }}/.zsh/zsh-autosuggestions"
      become: no

    - name: Remove zsh files
      shell: rm -rf {{ user_home }}/.zshrc {{ user_home }}/.config/shell
      become: no

    - name: clone dotfiles
      git:
        repo: https://github.com/aenrione/dotFiles
        dest: "{{ user_home }}/.dotfiles"
      ignore_errors: yes

    - name: Stow dotfiles
      shell: stow -t {{ user_home }} zsh
      args:
        chdir: "{{ user_home }}/.dotfiles"
      become: no

