# git clone https://github.com/AdnanHodzic/auto-cpufreq.git
# cd auto-cpufreq && sudo ./auto-cpufreq-installer
# Ansible playbook to install auto-cpufreq
---
- name: auto-cpufreq
  hosts: localhost
  become: yes
  tasks:
    - name: Install auto-cpufreq
      git:
        repo: https://github.com/AdnanHodzic/auto-cpufreq.git
        dest: /tmp/auto-cpufreq
      tags: auto-cpufreq
    - name: Run auto-cpufreq installer
      command: /tmp/auto-cpufreq/auto-cpufreq-installer
      tags: auto-cpufreq
    - name: pause to interact with installer
      pause:
        prompt: "Press Enter after you have interacted with the installer"
      tags: auto-cpufreq
    - name: Remove auto-cpufreq directory
      command: rm -rf /tmp/auto-cpufreq
      tags: auto-cpufreq

