---
- name: Install Brave Browser
  hosts: localhost
  become: yes
  tasks:
    - name: Install curl
      apt:
        name: curl
        state: present
        update_cache: yes

    - name: Download Brave Browser GPG key
      ansible.builtin.get_url:
        url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
        mode: '0644'

    - name: Add Brave Browser repository
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list.d/brave-browser-release.list
        line: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
        create: yes

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Brave Browser
      apt:
        name: brave-browser
        state: present

