---
- name: Install Docker on Ubuntu
  hosts: localhost
  become: yes
  vars:
    package_list: [docker-ce,docker-ce-cli,containerd.io,docker-buildx-plugin,docker-compose-plugin]

  tasks:

    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker Packages
      apt:
        name: "{{ item }}"
        state: present
      with_items: "{{ package_list }}"


    - name: Ensure Docker service is enabled and started
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Add user(s) to the docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      with_items: "{{ ansible_user_id }}"

    - name: Reload User Group
      shell: |
        sudo usermod -aG docker $USER
        newgrp docker

    - name: Ensure docker group has appropriate permissions
      file:
        path: /var/run/docker.sock
        owner: root
        group: docker
        mode: '0660'

    - name: Test Docker installation
      command: docker --version
      register: docker_version_output

    - name: Display Docker version
      debug:
        msg: "Docker version installed: {{ docker_version_output.stdout }}"
