---
- name: Setup custom DWM
  hosts: localhost
  become: yes
  vars:
    github_username: "aenrione"
    dwm_repo: "https://github.com/aenrione/suckless.git"
    stow_repo: "https://github.com/aenrione/dotFiles.git"
    target_directory: "{{ lookup('env', 'HOME') }}/mine/suckless"
    stow_directory: "{{ lookup('env', 'HOME') }}/mine/dotFiles"
    xsessions_dir: "/usr/share/xsessions"
  tasks:
    - name: Install dependencies for DWM
      apt:
        name:
          - libx11-dev
          - libxft-dev
          - libxinerama-dev
          - build-essential
          - pkg-config
          - libharfbuzz-dev
        state: present
        update_cache: yes

    - name: Clone DWM repository
      git:
        repo: "{{ dwm_repo }}"
        dest: "{{ target_directory }}"
        update: no

    - name: Build and install DWM
      shell: sudo make install
      args:
        chdir: "{{ target_directory }}/dwm"
      become: yes
    - name: Build and install ST
      shell: sudo make install
      args:
        chdir: "{{ target_directory }}/st"
      become: yes
    - name: Build and install DMENU
      shell: sudo make install
      args:
        chdir: "{{ target_directory }}/dmenu"
      become: yes

    - name: Create DWM desktop entry
      copy:
        content: |
          [Desktop Entry]
          Name=DWM
          Exec=/home/aenrione/.xinitrc
          Comment=Dynamic window manager
          Icon=dwm
          Type=XSession
        dest: "{{ xsessions_dir }}/dwm.desktop"
        owner: root
        group: root
        mode: '0644'

    - name: Clone dotfiles repository
      git:
        repo: "{{ stow_repo }}"
        dest: "{{ stow_directory }}"
        update: no

    - name: Stow dotfiles
      shell: stow --target="{{ lookup('env', 'HOME') }}" -S xsessions
      args:
        chdir: "{{ stow_directory }}"
      loop: 
        - folder_to_stow_1
        - folder_to_stow_2
        # Add more folders as needed
      become: yes
      environment:
        HOME: "{{ lookup('env', 'HOME') }}"

