---
- name: Install Fira Code Nerd Font
  hosts: localhost
  vars:
    font_dir: "~/.local/share/fonts"
    font_name: "FiraCode"
    release_url: "https://github.com/ryanoasis/nerd-fonts/releases/latest"
  tasks:
    - name: Ensure font directory exists
      file:
        path: "{{ font_dir }}"
        state: directory

    - name: Fetch the latest release page
      uri:
        url: "{{ release_url }}"
        return_content: yes
      register: release_page

    - name: Extract download URL for Fira Code zip file
      set_fact:
        download_url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v3.2.1/FiraCode.zip"

    - name: Download Fira Code Nerd Font
      get_url:
        url: "{{ download_url }}"
        dest: "/tmp/FiraCode.zip"

    - name: Unzip Fira Code Nerd Font
      unarchive:
        src: "/tmp/FiraCode.zip"
        dest: "{{ font_dir }}"
        remote_src: yes

    - name: Update font cache
      command: fc-cache -fv
      become: yes



