---
- name: Main playbook to install required tools
  hosts: localhost
  gather_facts: false

- import_playbook: required-tools/setup.yml
- import_playbook: required-tools/zsh_setup.yml
- import_playbook: required-tools/neovim.yml
- import_playbook: required-tools/tmux.yml
#- import_playbook: required-tools/docker.yml
- import_playbook: required-tools/ruby.yml
- import_playbook: required-tools/python.yml
# - import_playbook: required-tools/nodejs.yml
- import_playbook: required-tools/golang.yml
- import_playbook: required-tools/rustlang.yml
- import_playbook: required-tools/lazygit.yml
- import_playbook: required-tools/git_setup.yml

