---
- name: Ensure PostgreSQL is installed and configured
  hosts: localhost
  become: yes
  vars:
    postgresql_users:
      - name: root
        password: "{{ postgresql_root_password }}"
      - name: aenrione
        password: "{{ postgresql_user_password }}"
    postgresql_databases:
      - name: aenrione
        owner: aenrione
      - name: root
        owner: root
    database_privileges:
      - db: aenrione
        user: aenrione
        priv: "ALL"
      - db: root
        user: root
        priv: "ALL"
  vars_prompt:
    - name: "postgresql_root_password"
      prompt: "Enter the PostgreSQL root password"
      private: yes
    - name: "postgresql_user_password"
      prompt: "Enter the PostgreSQL aenrione password"
      private: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Ensure PostgreSQL is installed
      apt:
        name: postgresql
        state: present

    - name: Install psycopg2 dependency
      apt:
        name: python3-psycopg2
        state: present

    - name: Get PostgreSQL version
      command: psql --version
      register: psql_version_output

    - name: Set PostgreSQL version variable
      set_fact:
        postgresql_version: "{{ psql_version_output.stdout.split(' ')[-1].split('.')[0] }}"

    - name: Find pg_hba.conf path
      command: find /etc/postgresql -name pg_hba.conf
      register: pg_hba_conf_path_output

    - name: Set pg_hba.conf path variable
      set_fact:
        pg_hba_conf_path: "{{ pg_hba_conf_path_output.stdout_lines[0] }}"

    - name: Update pg_hba.conf for local connections to use md5 authentication for postgres user
      lineinfile:
        path: "{{ pg_hba_conf_path }}"
        regexp: '^local\s+all\s+postgres\s+\w+'
        line: 'local   all             postgres                                ident'
      notify: Restart PostgreSQL

    - name: Update pg_hba.conf for all local connections to use md5 authentication
      lineinfile:
        path: "{{ pg_hba_conf_path }}"
        regexp: '^local\s+all\s+all\s+\w+'
        line: 'local   all             all                                     ident'
      notify: Restart PostgreSQL

    - name: Restart PostgreSQL service
      service:
        name: postgresql
        state: restarted


    - name: Ensure PostgreSQL service is enabled and started
      service:
        name: postgresql
        state: started
        enabled: yes
      notify: Restart PostgreSQL

    - name: Ensure PostgreSQL users are present
      postgresql_user:
        name: "{{ item.name }}"
        password: "{{ item.password }}"
        role_attr_flags: "SUPERUSER"
        state: present
      with_items: "{{ postgresql_users }}"
      become_user: postgres  # Use postgres user to create other users

    - name: Ensure PostgreSQL databases are present
      postgresql_db:
        name: "{{ item.name }}"
        owner: "{{ item.owner }}"
        state: present
      with_items: "{{ postgresql_databases }}"
      become_user: postgres  # Use postgres user to create databases

    - name: Grant privileges on databases
      postgresql_privs:
        db: "{{ item.db }}"
        role: "{{ item.user }}"
        privs: "{{ item.priv }}"
        type: database
      with_items: "{{ database_privileges }}"
      become_user: postgres  # Use postgres user to grant privileges

  handlers:
    - name: Restart PostgreSQL
      systemd:
        name: postgresql
        state: restarted
        enabled: yes

