---
- name: Configure TMUX enviroment
  hosts: localhost
  tasks:
    - name: Clone tpm
      git:
        repo: https://github.com/tmux-plugins/tpm.git
        dest: ~/.tmux/plugins/tpm
    - name: Stow dotfiles
      shell: stow -t ~ tmux
      args:
        chdir: ~/my-github/mine/dotFiles

