require('keymaps')
require('bclose')
require('plugins.lazy')
require('plugins.misc')
require('plugins.lualine')
require('options')
require('helpers')
require('misc')
require('rails')
require('plugins.dap')
require('plugins.gitsigns')
require('plugins.tele')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.trouble')
require('plugins.zenmode')
require('plugins.neogit')
require('plugins.codesnap')
require('plugins.harpoon')
require('plugins.which-key')
require('plugins.transparent')
require('plugins.gpt')


-- vim: ts=8 sts=2 sw=2 et
